import { Controller, Get, Param, Res } from '@nestjs/common';
import { Response } from 'express';
import { StorageService } from '../services/storage.service';

/** Serves filesystem-backed files through signed URL tokens. */
@Controller('storage/files')
export class FilesystemFileController {
  /**
   * Create the filesystem signed-file controller.
   *
   * @param storage - Storage service that owns signed-read stream opening.
   */
  constructor(private readonly storage: StorageService) {}

  /** Verify a signed token and pipe the referenced file to the response. */
  /**
   * @param token - Filesystem signed URL token generated by `SignedUrlService`.
   * @param response - Express response that receives the file stream.
   * @throws When the operation cannot be completed.
   */
  @Get(':token')
  async serve(@Param('token') token: string, @Res() response: Response): Promise<void> {
    const stream = await this.storage.getSignedReadStream(token);
    stream.pipe(response);
  }
}
