replicaCount: 1
global:
  imageRegistry: ""
  imagePullSecrets: []
  commonLabels: {}
image:
  registry: ""
  repository: otwld/monorepo-starter/frontend
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: false
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
service:
  type: ClusterIP
  port: 4000
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: false
  minAvailable: 1
networkPolicy:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
extraEnv: []
extraEnvFrom: []
extraVolumes: []
extraVolumeMounts: []
